spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member-service/join/**
            - Method=PUT,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member-service/**
            - Method=GET,PUT,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/member-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product-service/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/product-service/(?<segment>.*), /$\{segment}
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product-service/wish/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/product-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-service/**
            - Method=POST,GET,PUT,PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/order-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/v1/stock-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/stock-service/(?<segment>.*), /$\{segment}
        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/v1/stock-service/**
            - Method=PUT,POST,PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/stock-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

token:
  expiration_time: 86400000
  secret: "01234567890123456789012345678901234567890123456789"
